### ISSUE TITLE
`EventGridParser` parse CloudEvent's directly

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#108]
**What feature would you like to have?**
We don't have the possibility to parse `CloudEvent`'s directly as we do with `EventGrid` events. It Could be a added-value if we have such a method on the `EventGridParser` as well; to only parse `CloudEvent`'s.

**Comment by tomkerkhove** [comment]
I'm really starting to question if we should still call this `EventGridParser` and not something more like `EventParser` or so because it feels wrong to add CloudEvent specific things to `EventGridParser`.

It does from a service standpoint but in the parsing context I'd more think in the payload/schema context than service.

Other than that, fine by me - Good feature suggestion.

**Comment by stijnmoreels** [comment]
I think this is not related anymore. We use an abstracted event instead.
