### ISSUE TITLE
Q: AuthenticationKey as SecureString?

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#43]
Since we're passing the authentication key in the builder quite a lot for guarding; should it be considered to pass it as a `SecureString`?

**Comment by tomkerkhove** [comment]
We could do that indeed but I'm not sure if we should even bother to be honest.

We need the secret in raw format to authenticate anyway so what would be the benefit of using it?

Honestly; I haven't seen a lot of Microsoft libraries, if not none, that use this.

**Comment by samneirinck** [comment]
I wouldn't do it, mainly because it gives a false assumption of it being _secure_. What is _secure_? Also, as stated by @tomkerkhove, I don't think many modern libraries still support this?

If you're interested into the details, have a listen here: https://www.youtube.com/watch?v=28xZ7Xb5MhE. 

[The docs are also relevant](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netcore-2.1#HowSecure)

**Comment by stijnmoreels** [comment]
Ok, was just thinking about the fact that we're passing the key quite a lot and the secure-string type would guard against multiple memory locations.

But thanks for info!

**Comment by tomkerkhove** [comment]
Thank you for the suggestion!
